# runtime java -jar xxx.jar --spring.profiles.active=test

# 默认配置
liquibase:
  enabled: true
  drop-first: true
  change-log: classpath:/dbmigraions/changelog.xml
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
---
# 开发配置
server:
  port: 8080
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root